### PR TITLE
add support for jsonschema

### PR DESCRIPTION
**Pull request by mehdipourfar**

### CODE REVIEW

**Comment by nnseva** [comment]
Hi @mehdipourfar ,

Thanx for your contribution,

What is the jsonschema for in this case? Could you please add some samples demonstrating how the jsonschema works into the `testapp` application?

**Comment by mehdipourfar** [comment]
> Hi @mehdipourfar ,
> 
> Thanx for your contribution,
> 
> What is the jsonschema for in this case? Could you please add some samples demonstrating how the jsonschema works into the `testapp` application?

Hi. There is an example here if you want to see how it works:
https://github.com/josdejong/jsoneditor/blob/develop/examples/07_json_schema_validation.html

I have written something like this in my admin model:

```python
    def formfield_for_dbfield(self, db_field, request, **kwargs):                                                                                                                             
        field = super().formfield_for_dbfield(db_field, request, **kwargs)                                                                                                                    
        if isinstance(field, forms.fields.JSONField):                                                                                                                                                                                                                                                                                                                                  
            field.widget = JSONEditor(jsonschema={"type": "object", "properties": {"some_key": {"type": "string"}}})                                                                                                                                  
        return field  
```

If you are okay with api, I can add some docs in ther project.

**Comment by mehdipourfar** [comment]
Just found out that it doesn't work as expected. I try to fix it in another commit.

**Comment by nnseva** [comment]
Hi @mehdipourfar ,

You probably meant JSONSchema support announced [in the JavaScript JSONEditor](https://github.com/josdejong/jsoneditor#tree-mode).

It could be a very nice extension to the widget. When your code will be ready, please add some explanations and/or examples to the README.md file for other people who would like to know how to use this extension.

**Comment by mehdipourfar** [comment]
Hi @nnseva ,
I have fixed that problem and added some usage info in the README file.

**Comment by nnseva** [comment]
Good job @mehdipourfar !

**Pull request merged**
