### PR TITLE
fix overlapping of widget and field label

### PR DESCRIPTION
**Pull request by mehdipourfar**

### CODE REVIEW

**Comment by nnseva** [comment]
Hi @mehdipourfar !

Thank you for the fix. Please provide some details about the problem which you are fixing - python and/or django versions where it appears, use cases, samples and/or screenshots demonstrating a visual glitch.

**Comment by mehdipourfar** [comment]
I use Django 2.1. In Django admin, JSON fields label were not visible due to overlapping with jsoneditor box. I simply set a margin on the jsoneditor and now it looks as it should.

**Comment by nnseva** [comment]
Thank you @mehdipourfar !

I see the #34 issue, it's probably the same problem. I should look for the more elegant way to do the same.

**Comment by nnseva** [comment]
Hi @mehdipourfar !

The fixed version of the django-jsoneditor has just been issued.

63459352c5ed531d19e1bd2cf540aa7cd55725d9

**Comment by mehdipourfar** [comment]
thanks a lot

**Pull request closed without merging**
